FROM ubuntu
RUN apt-get update
RUN apt-get install vim -y
#CMD: Specifies the command to run when a container is launched, if values are specified during the launch it will override the Dockerfile value 
CMD ["echo","Sanjeeva"]
#ENTRYPOINT: This also same as CMD but 
